### ISSUE TITLE
can you support cluster mode?

### ISSUE THREAD

**Issue by family2hu** [node-casbin/redis-watcher#5]
In my company, cluster mode is required, would you please add cluster connection? Thanks a lot!

**Comment by hsluoyz** [comment]
@zhmushan @stu01509

/cc @nodece

**Comment by nodece** [comment]
@family2hu I submitted a PR: https://github.com/node-casbin/redis-watcher/pull/6, could you review the PR?

**Comment by nodece** [comment]
@family2hu `@casbin/redis-watcher` has been released on NPM, it supports the use of Redis cluster.

**Comment by hsluoyz** [comment]
https://www.npmjs.com/package/@casbin/redis-watcher
